// shared/constants/index.js

// Importar y re-exportar todos los constantes
const {
  MEDIA_TYPES,
  LIBRARY_TYPES,
  VIDEO_FORMATS,
  AUDIO_FORMATS,
  IMAGE_FORMATS,
  FILE_EXTENSIONS,
  STREAMING_QUALITIES,
  STREAMING_PROTOCOLS,
} = require("./mediaTypes");

const {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
} = require("./errorCodes");

const { DEFAULT_CONFIG, CACHE_TTL, REGEX } = require("./config");

// Constantes de estado HTTP
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

// Mapeo de códigos de error a estados HTTP
const ERROR_TO_HTTP_STATUS = {
  // Auth errors
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_EXPIRED_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_INVALID_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_MISSING_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.AUTH_EMAIL_IN_USE]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.AUTH_USERNAME_IN_USE]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.AUTH_INVALID_INVITATION]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.AUTH_EXPIRED_INVITATION]: HTTP_STATUS.BAD_REQUEST,

  // Resource errors
  [ERROR_CODES.RESOURCE_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.RESOURCE_CONFLICT]: HTTP_STATUS.CONFLICT,

  // Validation errors
  [ERROR_CODES.VALIDATION_FAILED]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.VALIDATION_INVALID_VALUE]: HTTP_STATUS.BAD_REQUEST,

  // Library errors
  [ERROR_CODES.LIBRARY_ACCESS_DENIED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.LIBRARY_PATH_EXISTS]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.LIBRARY_PATH_NOT_FOUND]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.LIBRARY_PATH_NOT_READABLE]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.LIBRARY_SCAN_IN_PROGRESS]: HTTP_STATUS.CONFLICT,

  // Media errors
  [ERROR_CODES.MEDIA_FILE_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.MEDIA_UNSUPPORTED_FORMAT]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.MEDIA_TRANSCODING_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.MEDIA_STREAMING_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,

  // System errors
  [ERROR_CODES.SYSTEM_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SYSTEM_DATABASE_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SYSTEM_DISK_FULL]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SYSTEM_IO_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SYSTEM_NETWORK_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SYSTEM_SERVICE_UNAVAILABLE]: HTTP_STATUS.SERVICE_UNAVAILABLE,
};

module.exports = {
  // Re-exportar constantes de otros archivos
  MEDIA_TYPES,
  LIBRARY_TYPES,
  VIDEO_FORMATS,
  AUDIO_FORMATS,
  IMAGE_FORMATS,
  FILE_EXTENSIONS,
  STREAMING_QUALITIES,
  STREAMING_PROTOCOLS,
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  DEFAULT_CONFIG,
  CACHE_TTL,
  REGEX,

  // Constantes definidas en este archivo
  HTTP_STATUS,
  ERROR_TO_HTTP_STATUS,
};
